language: php

php:
  - 7.4

services:
  - mysql

install:
  - composer install
  - composer update
  - composer dump -o
  - mkdir tests/cache

cache:
  directories:
  - vendor

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_success:
  - composer require php-coveralls/php-coveralls
  - travis_retry php vendor/bin/php-coveralls