language: php

php:
  - 7.2.5
  - 7.1.9

matrix:
  allow_failures:
    - php: 7.1.9

services:
  - mysql

install:
  - composer require consolidation/robo:^1.3
  - composer install
  - composer update
  - composer dump -o
  - ./vendor/bin/robo creat:tmp-dir

cache:
  directories:
  - vendor

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_success:
  - composer require php-coveralls/php-coveralls
  - travis_retry php vendor/bin/php-coveralls